"""Hindi + Telugu keyword sets (native script and common romanized/Hinglish forms),
plus localized summaries and recommendations."""

KEYWORDS = {
    "hi": {
        "urgency": ["turant", "abhi", "jaldi", "aaj hi", "antim mauka", "तुरंत", "अभी", "जल्दी",
                    "आज ही", "अंतिम मौका", "24 घंटे", "खाता बंद"],
        "financial_lure": ["inaam", "lottery", "jeet", "paisa double", "guaranteed return", "pakka munafa",
                           "इनाम", "लॉटरी", "जीत", "पैसे दुगने", "गारंटी", "पक्का मुनाफा", "बिना जोखिम"],
        "credential_request": ["otp batao", "kyc update", "kyc", "pin", "password", "aadhaar number",
                               "ओटीपी", "केवाईसी", "पिन", "पासवर्ड", "आधार", "पैन कार्ड", "बैंक डिटेल"],
        "fake_authority": ["rbi", "sebi", "income tax", "sarkari yojana", "sarkar", "बैंक मैनेजर",
                           "आरबीआई", "सेबी", "आयकर", "सरकारी योजना", "सरकार", "पुलिस", "गिरफ्तारी"],
        "investment_scam": ["share tips", "trading tips", "pakka tip", "insider", "crypto double",
                            "शेयर टिप्स", "ट्रेडिंग टिप्स", "पक्की टिप", "रोज कमाओ", "व्हाट्सएप ग्रुप", "टेलीग्राम ग्रुप"],
        "phishing_link": ["link par click", "लिंक पर क्लिक", "यहाँ क्लिक", "ऐप डाउनलोड"],
        "pressure_tactics": ["sirf aaj", "kisi ko mat batana", "gupt", "सिर्फ आज", "किसी को मत बताना",
                             "गुप्त", "सीमित सीटें", "सिर्फ आपके लिए"],
    },
    "te": {
        "urgency": ["ventane", "ippude", "tvaraga", "ఈ రోజే", "వెంటనే", "ఇప్పుడే", "త్వరగా",
                    "చివరి అవకాశం", "24 గంటల్లో", "ఖాతా బ్లాక్"],
        "financial_lure": ["bahumati", "lottery", "రెట్టింపు", "బహుమతి", "లాటరీ", "గెలిచారు",
                           "హామీ లాభం", "రిస్క్ లేదు", "100% లాభం"],
        "credential_request": ["otp cheppandi", "kyc", "ఓటీపీ", "కేవైసీ", "పిన్", "పాస్‌వర్డ్",
                               "ఆధార్", "పాన్ కార్డ్", "బ్యాంక్ వివరాలు"],
        "fake_authority": ["rbi", "sebi", "ఆర్‌బీఐ", "సెబీ", "ఆదాయపు పన్ను", "ప్రభుత్వ పథకం",
                           "పోలీస్", "అరెస్ట్", "బ్యాంక్ మేనేజర్"],
        "investment_scam": ["షేర్ టిప్స్", "ట్రేడింగ్ టిప్స్", "ఇన్‌సైడర్", "క్రిప్టో డబుల్",
                            "రోజూ సంపాదించండి", "వాట్సాప్ గ్రూప్", "టెలిగ్రామ్ గ్రూప్"],
        "phishing_link": ["లింక్ క్లిక్", "ఇక్కడ క్లిక్", "యాప్ డౌన్‌లోడ్"],
        "pressure_tactics": ["ఈ రోజు మాత్రమే", "ఎవరికీ చెప్పకండి", "రహస్యం", "పరిమిత సీట్లు", "మీకు మాత్రమే"],
    },
}

MESSAGES = {
    "en": {
        "HIGH": "This message shows several strong signs of a scam. Do not act on it.",
        "SUSPICIOUS": "This message has some warning signs. Verify it through an official source before doing anything.",
        "SAFE": "We found no strong scam signs. This is not a guarantee: stay careful and never share OTP or PIN.",
        "recs_high": ["Do not click any links or download any app", "Never share OTP, PIN, CVV or password with anyone",
                      "Do not send money or pay any 'fee'", "Block the sender and report it at cybercrime.gov.in or call 1930"],
        "recs_sus": ["Do not click links until you verify the sender", "Call your bank or broker using the number on their official website",
                     "Check SEBI-registered entities at sebi.gov.in", "Talk to a family member before acting"],
        "recs_safe": ["Still avoid sharing OTP or PIN", "Verify unknown senders", "When in doubt, ask someone you trust"],
        "uncertain": "Automated checks can miss new scams or flag genuine messages. Use this as a guide, not proof.",
    },
    "hi": {
        "HIGH": "इस संदेश में धोखाधड़ी के कई मजबूत संकेत हैं। इस पर कोई कार्रवाई न करें।",
        "SUSPICIOUS": "इस संदेश में कुछ चेतावनी संकेत हैं। कुछ भी करने से पहले आधिकारिक स्रोत से जाँच करें।",
        "SAFE": "कोई मजबूत धोखाधड़ी संकेत नहीं मिला। यह गारंटी नहीं है: सावधान रहें और OTP/PIN कभी साझा न करें।",
        "recs_high": ["किसी लिंक पर क्लिक न करें और कोई ऐप डाउनलोड न करें", "OTP, PIN, CVV या पासवर्ड किसी को न बताएं",
                      "कोई पैसा या 'फीस' न भेजें", "भेजने वाले को ब्लॉक करें और cybercrime.gov.in पर या 1930 पर रिपोर्ट करें"],
        "recs_sus": ["भेजने वाले की जाँच होने तक लिंक पर क्लिक न करें", "बैंक/ब्रोकर की आधिकारिक वेबसाइट के नंबर पर कॉल करें",
                     "sebi.gov.in पर SEBI-पंजीकृत संस्था जाँचें", "कार्रवाई से पहले परिवार से बात करें"],
        "recs_safe": ["फिर भी OTP या PIN साझा न करें", "अजनबी भेजने वालों की जाँच करें", "शक हो तो किसी भरोसेमंद से पूछें"],
        "uncertain": "स्वचालित जाँच नए घोटाले चूक सकती है या असली संदेश को संदिग्ध बता सकती है। इसे सुझाव मानें, सबूत नहीं।",
    },
    "te": {
        "HIGH": "ఈ సందేశంలో మోసం యొక్క బలమైన సంకేతాలు ఉన్నాయి. దీనిపై ఏ చర్యా తీసుకోకండి.",
        "SUSPICIOUS": "ఈ సందేశంలో కొన్ని హెచ్చరిక సంకేతాలు ఉన్నాయి. ఏదైనా చేసే ముందు అధికారిక వనరు ద్వారా ధృవీకరించండి.",
        "SAFE": "బలమైన మోసపు సంకేతాలు కనిపించలేదు. ఇది హామీ కాదు: జాగ్రత్తగా ఉండండి, OTP/PIN ఎప్పుడూ పంచుకోకండి.",
        "recs_high": ["ఏ లింక్ క్లిక్ చేయకండి, ఏ యాప్ డౌన్‌లోడ్ చేయకండి", "OTP, PIN, CVV, పాస్‌వర్డ్ ఎవరికీ చెప్పకండి",
                      "డబ్బు లేదా 'ఫీజు' పంపకండి", "పంపినవారిని బ్లాక్ చేసి cybercrime.gov.in లో లేదా 1930 కి రిపోర్ట్ చేయండి"],
        "recs_sus": ["పంపినవారిని ధృవీకరించే వరకు లింక్ క్లిక్ చేయకండి", "బ్యాంక్/బ్రోకర్ అధికారిక వెబ్‌సైట్‌లోని నంబర్‌కు కాల్ చేయండి",
                     "sebi.gov.in లో SEBI-నమోదిత సంస్థను తనిఖీ చేయండి", "చర్య తీసుకునే ముందు కుటుంబంతో మాట్లాడండి"],
        "recs_safe": ["అయినా OTP/PIN పంచుకోకండి", "తెలియని పంపినవారిని ధృవీకరించండి", "సందేహం ఉంటే నమ్మకమైన వారిని అడగండి"],
        "uncertain": "ఆటోమేటిక్ తనిఖీలు కొత్త మోసాలను గుర్తించకపోవచ్చు లేదా నిజమైన సందేశాలను తప్పుగా గుర్తించవచ్చు. దీన్ని సూచనగా మాత్రమే చూడండి.",
    },
}
