// Learn page content (EN / HI / TE). Example domains and messages are made up for teaching.
// Official links: re-check each URL before you submit.
const LEARN = {
  links: [
    { url: "https://cybercrime.gov.in", key: "cyber" },
    { url: "https://scores.sebi.gov.in", key: "scores" },
    { url: "https://investor.sebi.gov.in", key: "investor" },
    { url: "https://www.sebi.gov.in", key: "sebi" },
    { url: "https://www.rbi.org.in", key: "rbi" },
    { url: "https://rbikehtahai.rbi.org.in", key: "rbikh" },
  ],
  en: {
    heading: "Learn to spot scams",
    intro: "Scams change their words, but the tricks stay the same. Know these and you are already safer.",
    phrases: { title: "Phrases scammers use", items: [
      { q: "Your KYC expires today. Update now at the link or your account will be blocked.", why: "Fake deadline plus a threat. Banks do not block accounts by SMS link." },
      { q: "Join our VIP group. Guaranteed 300% returns every week. Risk-free.", why: "No real investment can guarantee profit. Big fixed returns are the classic bait." },
      { q: "Share the OTP you just received to confirm your refund.", why: "An OTP gives access to your money. No bank or official ever asks for it." },
      { q: "SEBI notice: legal action against you. Pay Rs 5000 to settle today.", why: "Pretending to be a regulator to scare you. SEBI does not collect fines by message." },
      { q: "Congratulations, you won! Pay a small processing fee to claim your prize.", why: "You never pay to receive a prize. The fee is the scam." },
      { q: "Don't tell anyone. Special tip only for you, valid today only.", why: "Secrecy stops you from asking family or an expert. Pressure and secrecy go together." },
    ] },
    domains: { title: "Fake website patterns", items: [
      { q: "hdfc-bank-kyc.xyz", why: "Bank name glued to extra words on a cheap ending (.xyz, .top, .tk). Real banks use their own official address." },
      { q: "sbi.co.in.verify-now.top", why: "The real name appears first, but the real site is the LAST part before the slash: verify-now.top." },
      { q: "hdfcbnk.com or sbl-online.com", why: "One letter swapped or changed (i to l, o to 0). Read slowly." },
      { q: "bit.ly/3xYz or tinyurl.com/abc", why: "Short links hide where you will land. Do not open them from unknown senders." },
      { q: "http://192.168.10.5/login", why: "Numbers instead of a name, or no padlock (http), are warning signs." },
      { q: "kyc-update.apk", why: "A file ending in .apk is an app outside the Play Store. It can read your SMS and OTPs." },
    ] },
    steps: { title: "If you meet a scam: what to do", items: [
      "Do not click, reply, or call back. Do not share any OTP or PIN.",
      "Take a screenshot and keep the message, number and link as proof.",
      "Lost money? Call 1930 immediately. Fast reports give the best chance to freeze the money.",
      "Report at cybercrime.gov.in with your screenshots and transaction details.",
      "Tell your bank so they can block cards or accounts. Call the number on their official website.",
      "For investment or market fraud, also complain on SEBI SCORES (scores.sebi.gov.in).",
    ] },
    resources: { title: "Official resources", items: {
      cyber: ["National Cyber Crime Reporting Portal", "Report online fraud. Helpline: 1930."],
      scores: ["SEBI SCORES", "Complain about brokers, companies or market fraud."],
      investor: ["SEBI Investor Website", "Investor education, alerts and safety tips."],
      sebi: ["SEBI", "The securities market regulator."],
      rbi: ["Reserve Bank of India", "Banking rules and public notices."],
      rbikh: ["RBI Kehta Hai", "Simple awareness on frauds and banking safety."],
    } },
  },
  hi: {
    heading: "धोखाधड़ी पहचानना सीखें",
    intro: "ठग शब्द बदलते हैं, पर तरीके वही रहते हैं। इन्हें जान लें तो आप पहले से ज़्यादा सुरक्षित हैं।",
    phrases: { title: "ठग कौन से वाक्य इस्तेमाल करते हैं", items: [
      { q: "आपका KYC आज खत्म हो रहा है। अभी लिंक पर अपडेट करें वरना खाता बंद हो जाएगा।", why: "झूठी समय सीमा और धमकी। बैंक SMS लिंक से खाता बंद नहीं करते।" },
      { q: "हमारे VIP ग्रुप से जुड़ें। हर हफ्ते 300% पक्का मुनाफा। बिना जोखिम।", why: "कोई असली निवेश मुनाफे की गारंटी नहीं दे सकता। बड़ा पक्का मुनाफा ठगी का पुराना चारा है।" },
      { q: "रिफंड की पुष्टि के लिए अभी आया OTP बताइए।", why: "OTP से आपके पैसे तक पहुँच मिलती है। कोई बैंक या अधिकारी इसे कभी नहीं माँगता।" },
      { q: "SEBI नोटिस: आपके खिलाफ कानूनी कार्रवाई। आज ही 5000 रुपये भरकर मामला निपटाएँ।", why: "डराने के लिए नियामक बनना। SEBI संदेश से जुर्माना नहीं वसूलता।" },
      { q: "बधाई, आप जीत गए! इनाम पाने के लिए थोड़ी प्रोसेसिंग फीस भरें।", why: "इनाम पाने के लिए पैसे नहीं देने पड़ते। वह फीस ही ठगी है।" },
      { q: "किसी को मत बताना। सिर्फ आपके लिए खास टिप, सिर्फ आज।", why: "गोपनीयता आपको परिवार या विशेषज्ञ से पूछने से रोकती है। दबाव और गोपनीयता साथ आते हैं।" },
    ] },
    domains: { title: "नकली वेबसाइट के पैटर्न", items: [
      { q: "hdfc-bank-kyc.xyz", why: "बैंक के नाम के साथ अतिरिक्त शब्द और सस्ता अंत (.xyz, .top, .tk)। असली बैंक अपना आधिकारिक पता इस्तेमाल करते हैं।" },
      { q: "sbi.co.in.verify-now.top", why: "असली नाम पहले दिखता है, पर असली साइट स्लैश से पहले का आखिरी हिस्सा है: verify-now.top।" },
      { q: "hdfcbnk.com या sbl-online.com", why: "एक अक्षर बदला हुआ (i की जगह l, o की जगह 0)। धीरे पढ़ें।" },
      { q: "bit.ly/3xYz या tinyurl.com/abc", why: "छोटे लिंक छुपाते हैं कि आप कहाँ पहुँचेंगे। अनजान भेजने वाले का छोटा लिंक न खोलें।" },
      { q: "http://192.168.10.5/login", why: "नाम की जगह नंबर, या ताला (https) न होना चेतावनी है।" },
      { q: "kyc-update.apk", why: ".apk फाइल प्ले स्टोर के बाहर का ऐप है। वह आपके SMS और OTP पढ़ सकता है।" },
    ] },
    steps: { title: "ठगी का सामना हो तो क्या करें", items: [
      "क्लिक, जवाब या वापस कॉल न करें। OTP या PIN किसी को न बताएं।",
      "स्क्रीनशॉट लें और संदेश, नंबर और लिंक सबूत के तौर पर रखें।",
      "पैसे गए? तुरंत 1930 पर कॉल करें। जल्दी रिपोर्ट से पैसे रुकवाने की संभावना बढ़ती है।",
      "स्क्रीनशॉट और लेन-देन की जानकारी के साथ cybercrime.gov.in पर रिपोर्ट करें।",
      "अपने बैंक को बताएँ ताकि वे कार्ड या खाता ब्लॉक करें। उनकी आधिकारिक वेबसाइट के नंबर पर कॉल करें।",
      "निवेश या बाजार धोखाधड़ी में SEBI SCORES (scores.sebi.gov.in) पर भी शिकायत करें।",
    ] },
    resources: { title: "आधिकारिक संसाधन", items: {
      cyber: ["राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल", "ऑनलाइन ठगी रिपोर्ट करें। हेल्पलाइन: 1930।"],
      scores: ["SEBI SCORES", "ब्रोकर, कंपनी या बाजार धोखाधड़ी की शिकायत करें।"],
      investor: ["SEBI निवेशक वेबसाइट", "निवेशक शिक्षा, अलर्ट और सुरक्षा सुझाव।"],
      sebi: ["SEBI", "प्रतिभूति बाजार का नियामक।"],
      rbi: ["भारतीय रिज़र्व बैंक", "बैंकिंग नियम और सार्वजनिक सूचनाएँ।"],
      rbikh: ["RBI कहता है", "ठगी और बैंकिंग सुरक्षा पर सरल जागरूकता।"],
    } },
  },
  te: {
    heading: "మోసాలను గుర్తించడం నేర్చుకోండి",
    intro: "మోసగాళ్ళు మాటలు మారుస్తారు, కానీ పద్ధతులు అవే. ఇవి తెలిస్తే మీరు ఇప్పటికే సురక్షితంగా ఉన్నట్లే.",
    phrases: { title: "మోసగాళ్ళు వాడే మాటలు", items: [
      { q: "మీ KYC ఈ రోజు ముగుస్తుంది. వెంటనే లింక్‌లో అప్‌డేట్ చేయండి, లేకపోతే ఖాతా బ్లాక్ అవుతుంది.", why: "నకిలీ గడువు, బెదిరింపు. బ్యాంకులు SMS లింక్‌తో ఖాతాను బ్లాక్ చేయవు." },
      { q: "మా VIP గ్రూప్‌లో చేరండి. ప్రతి వారం 300% హామీ లాభం. రిస్క్ లేదు.", why: "ఏ నిజమైన పెట్టుబడీ లాభానికి హామీ ఇవ్వదు. పెద్ద స్థిర లాభం మోసాల పాత ఎర." },
      { q: "రీఫండ్ నిర్ధారణకు ఇప్పుడే వచ్చిన OTP చెప్పండి.", why: "OTP వల్ల మీ డబ్బుకు ప్రవేశం దొరుకుతుంది. ఏ బ్యాంకూ, అధికారీ దాన్ని అడగరు." },
      { q: "SEBI నోటీసు: మీపై చట్టపరమైన చర్య. ఈ రోజే రూ. 5000 చెల్లించి పరిష్కరించుకోండి.", why: "భయపెట్టడానికి నియంత్రణ సంస్థలా నటించడం. SEBI సందేశం ద్వారా జరిమానా వసూలు చేయదు." },
      { q: "అభినందనలు, మీరు గెలిచారు! బహుమతి పొందడానికి చిన్న ప్రాసెసింగ్ ఫీజు చెల్లించండి.", why: "బహుమతి పొందడానికి డబ్బు కట్టాల్సిన పనిలేదు. ఆ ఫీజే మోసం." },
      { q: "ఎవరికీ చెప్పకండి. మీకు మాత్రమే ప్రత్యేక టిప్, ఈ రోజు మాత్రమే.", why: "రహస్యం వల్ల కుటుంబాన్ని లేదా నిపుణులను అడగలేరు. ఒత్తిడి, రహస్యం కలిసి వస్తాయి." },
    ] },
    domains: { title: "నకిలీ వెబ్‌సైట్ పద్ధతులు", items: [
      { q: "hdfc-bank-kyc.xyz", why: "బ్యాంక్ పేరుకు అదనపు పదాలు, చౌక ముగింపు (.xyz, .top, .tk). నిజమైన బ్యాంకులు తమ అధికారిక చిరునామా వాడతాయి." },
      { q: "sbi.co.in.verify-now.top", why: "నిజమైన పేరు మొదట కనిపిస్తుంది, కానీ అసలు సైట్ స్లాష్ ముందు చివరి భాగం: verify-now.top." },
      { q: "hdfcbnk.com లేదా sbl-online.com", why: "ఒక అక్షరం మార్చారు (i బదులు l, o బదులు 0). నెమ్మదిగా చదవండి." },
      { q: "bit.ly/3xYz లేదా tinyurl.com/abc", why: "చిన్న లింకులు మీరు ఎక్కడికి వెళ్తారో దాచేస్తాయి. తెలియని వారి చిన్న లింక్ తెరవకండి." },
      { q: "http://192.168.10.5/login", why: "పేరు బదులు అంకెలు, లేదా తాళం (https) లేకపోవడం హెచ్చరిక." },
      { q: "kyc-update.apk", why: ".apk ఫైల్ ప్లే స్టోర్ బయటి యాప్. అది మీ SMS, OTP లను చదవగలదు." },
    ] },
    steps: { title: "మోసం ఎదురైతే ఏం చేయాలి", items: [
      "క్లిక్ చేయకండి, బదులివ్వకండి, తిరిగి కాల్ చేయకండి. OTP, PIN ఎవరికీ చెప్పకండి.",
      "స్క్రీన్‌షాట్ తీసి సందేశం, నంబర్, లింక్‌ను రుజువుగా ఉంచండి.",
      "డబ్బు పోయిందా? వెంటనే 1930 కి కాల్ చేయండి. త్వరగా రిపోర్ట్ చేస్తే డబ్బు ఆపే అవకాశం ఎక్కువ.",
      "స్క్రీన్‌షాట్లు, లావాదేవీ వివరాలతో cybercrime.gov.in లో రిపోర్ట్ చేయండి.",
      "మీ బ్యాంక్‌కు చెప్పండి, వారు కార్డ్ లేదా ఖాతాను బ్లాక్ చేస్తారు. వారి అధికారిక వెబ్‌సైట్‌లోని నంబర్‌కు కాల్ చేయండి.",
      "పెట్టుబడి లేదా మార్కెట్ మోసం అయితే SEBI SCORES (scores.sebi.gov.in) లో కూడా ఫిర్యాదు చేయండి.",
    ] },
    resources: { title: "అధికారిక వనరులు", items: {
      cyber: ["జాతీయ సైబర్ క్రైమ్ రిపోర్టింగ్ పోర్టల్", "ఆన్‌లైన్ మోసాన్ని రిపోర్ట్ చేయండి. హెల్ప్‌లైన్: 1930."],
      scores: ["SEBI SCORES", "బ్రోకర్లు, కంపెనీలు లేదా మార్కెట్ మోసంపై ఫిర్యాదు చేయండి."],
      investor: ["SEBI ఇన్వెస్టర్ వెబ్‌సైట్", "ఇన్వెస్టర్ విద్య, హెచ్చరికలు, భద్రతా సూచనలు."],
      sebi: ["SEBI", "సెక్యూరిటీస్ మార్కెట్ నియంత్రణ సంస్థ."],
      rbi: ["భారతీయ రిజర్వ్ బ్యాంక్", "బ్యాంకింగ్ నియమాలు, ప్రజా నోటీసులు."],
      rbikh: ["RBI కెహతా హై", "మోసాలు, బ్యాంకింగ్ భద్రతపై సులభమైన అవగాహన."],
    } },
  },
};
